### ISSUE TITLE
problem in build

### ISSUE THREAD

**Issue by Aminmalek** [docker-snap/docker-snap#129]
I have this problem when building a Java app
```
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 203, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3/dist-packages/compose/metrics/decorator.py", line 18, in wrapper
    result = fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 368, in build
    self.project.build(
  File "/usr/lib/python3/dist-packages/compose/project.py", line 519, in build
    build_service(service)
  File "/usr/lib/python3/dist-packages/compose/project.py", line 501, in build_service
    service.build(no_cache, pull, force_rm, memory, build_args, gzip, rm, silent, cli, progress)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 1111, in build
    return builder.build(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 1948, in build
    with open(iidfile) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmphcevs75f'
```

**Comment by zhsj** [comment]
We have removed the python version of compose in latest/candidate channel (replaced by the go version), could you try that?

**Comment by Aminmalek** [comment]
> We have removed the python version of compose in latest/candidate channel (replaced by the go version), could you try that?

How can I have that version?
I installed it by command snap install docker

**Comment by zhsj** [comment]
> How can I have that version? I installed it by command snap install docker

You can try with `snap refresh docker --candidate`

**Comment by xnox** [comment]
Did that work for you? Can I close this issue?

**Comment by Aminmalek** [comment]
> Did that work for you? Can I close this issue?

yes, thanks
