### ISSUE TITLE
Strict /tmp isolation prevents use of vscode devcontainers

### ISSUE THREAD

**Issue by aebrahim** [docker-snap/docker-snap#58]
It looks like vscode writes `Dockerfile`s into `/tmp/vsch`, but the strict snap isolation of /tmp means only an empty directory it seen.

Is there any way around this behavior?

**Comment by tepene** [comment]
I second that. Launching a VSCode devcontainer on docker snap fails with `unable to prepare context: path "/tmp/vsch" not found`

```
c10f59933ab3: Pull complete 
[2022-05-18T09:05:05.337Z] Digest: sha256:21a12816fcadaa16dabb4ba0e8c358361d02ea062b1b89db8786eb67173489d0
[2022-05-18T09:05:05.360Z] Status: Downloaded newer image for mcr.microsoft.com/vscode/devcontainers/python:0-3.10
[2022-05-18T09:05:05.392Z]  ---> 53f071753966
Step 3/4 : ARG NODE_VERSION="none"
[2022-05-18T09:05:06.294Z]  ---> Running in 66a74d52d211
[2022-05-18T09:05:06.537Z] Removing intermediate container 66a74d52d211
 ---> dfc3f1c61c72
Step 4/4 : RUN if [ "${NODE_VERSION}" != "none" ]; then su vscode -c "umask 0002 && . /usr/local/share/nvm/nvm.sh && nvm install ${NODE_VERSION} 2>&1"; fi
[2022-05-18T09:05:06.621Z]  ---> Running in 4831a254cc0f
[2022-05-18T09:05:08.607Z] Removing intermediate container 4831a254cc0f
 ---> bc247ec3a3c6
Successfully built bc247ec3a3c6
[2022-05-18T09:05:08.622Z] Successfully tagged vsc-test-29fce7ed9d9f5e5860a95092dd05a252:latest
[2022-05-18T09:05:08.637Z] Stop (144568 ms): Run: docker build -f /home/lus/Code/test/.devcontainer/Dockerfile -t vsc-test-29fce7ed9d9f5e5860a95092dd05a252 --build-arg VARIANT=3.10 --build-arg NODE_VERSION=none /home/lus/Code/test
[2022-05-18T09:05:08.644Z] Start: Run: docker inspect --type image vsc-test-29fce7ed9d9f5e5860a95092dd05a252
[2022-05-18T09:05:09.358Z] Stop (714 ms): Run: docker inspect --type image vsc-test-29fce7ed9d9f5e5860a95092dd05a252
[2022-05-18T09:05:09.362Z] Start: Run: docker build -f /tmp/vsch/updateUID.Dockerfile-0.234.0 -t vsc-test-29fce7ed9d9f5e5860a95092dd05a252-uid --build-arg BASE_IMAGE=vsc-test-29fce7ed9d9f5e5860a95092dd05a252 --build-arg REMOTE_USER=vscode --build-arg NEW_UID=1000 --build-arg NEW_GID=1000 --build-arg IMAGE_USER=root /tmp/vsch
[2022-05-18T09:05:09.560Z] unable to prepare context: path "/tmp/vsch" not found
[2022-05-18T09:05:09.565Z] Stop (203 ms): Run: docker build -f /tmp/vsch/updateUID.Dockerfile-0.234.0 -t vsc-test-29fce7ed9d9f5e5860a95092dd05a252-uid --build-arg BASE_IMAGE=vsc-test-29fce7ed9d9f5e5860a95092dd05a252 --build-arg REMOTE_USER=vscode --build-arg NEW_UID=1000 --build-arg NEW_GID=1000 --build-arg IMAGE_USER=root /tmp/vsch
[2022-05-18T09:05:09.568Z] Error: Command failed: docker build -f /tmp/vsch/updateUID.Dockerfile-0.234.0 -t vsc-test-29fce7ed9d9f5e5860a95092dd05a252-uid --build-arg BASE_IMAGE=vsc-test-29fce7ed9d9f5e5860a95092dd05a252 --build-arg REMOTE_USER=vscode --build-arg NEW_UID=1000 --build-arg NEW_GID=1000 --build-arg IMAGE_USER=root /tmp/vsch
[2022-05-18T09:05:09.568Z]     at IR (/home/lus/.vscode/extensions/ms-vscode-remote.remote-containers-0.234.0/dist/spec-node/devContainersSpecCLI.js:221:995)
[2022-05-18T09:05:09.569Z]     at zy (/home/lus/.vscode/extensions/ms-vscode-remote.remote-containers-0.234.0/dist/spec-node/devContainersSpecCLI.js:221:933)
[2022-05-18T09:05:09.569Z]     at runMicrotasks (<anonymous>)
[2022-05-18T09:05:09.569Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-05-18T09:05:09.569Z]     at async $R (/home/lus/.vscode/extensions/ms-vscode-remote.remote-containers-0.234.0/dist/spec-node/devContainersSpecCLI.js:226:2007)
[2022-05-18T09:05:09.569Z]     at async Zy (/home/lus/.vscode/extensions/ms-vscode-remote.remote-containers-0.234.0/dist/spec-node/devContainersSpecCLI.js:226:3112)
[2022-05-18T09:05:09.570Z]     at async BR (/home/lus/.vscode/extensions/ms-vscode-remote.remote-containers-0.234.0/dist/spec-node/devContainersSpecCLI.js:226:12448)
[2022-05-18T09:05:09.570Z]     at async qR (/home/lus/.vscode/extensions/ms-vscode-remote.remote-containers-0.234.0/dist/spec-node/devContainersSpecCLI.js:226:12204)
[2022-05-18T09:05:09.583Z] Stop (145978 ms): Run: /var/lib/snapd/snap/code/96/usr/share/code/code /home/lus/.vscode/extensions/ms-vscode-remote.remote-containers-0.234.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/lus/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-data-folder .vscode-server/data/Machine --container-system-data-folder /var/vscode-server --workspace-folder /home/lus/Code/test --workspace-mount-consistency cached --id-label vsch.local.folder=/home/lus/Code/test --id-label vsch.quality=stable --log-level debug --log-format json --config /home/lus/Code/test/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-05-18T09:05:09.585Z] Exit code 1
[2022-05-18T09:05:09.595Z] Command failed: /var/lib/snapd/snap/code/96/usr/share/code/code /home/lus/.vscode/extensions/ms-vscode-remote.remote-containers-0.234.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/lus/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-data-folder .vscode-server/data/Machine --container-system-data-folder /var/vscode-server --workspace-folder /home/lus/Code/test --workspace-mount-consistency cached --id-label vsch.local.folder=/home/lus/Code/test --id-label vsch.quality=stable --log-level debug --log-format json --config /home/lus/Code/test/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-05-18T09:05:09.595Z] Exit code 1
```
Related issue can be found here: <https://github.com/microsoft/vscode-remote-release/issues/5865>
Is there a way to allow docker snap to access /tmp?

**Comment by kinghat** [comment]
is it possible to give this snap access to the `/tmp` dir?

**Comment by locnnil** [comment]
It would be possible to give `docker-snap` access to `/tmp` using the snap `system-files` interface.
